### Create new product
POST http://localhost:3001/api/product
Content-Type: application/json

{
  "type": "PRODUCT",
  "price": 9.99,
  "stock": 2,
  "thumbnail": "https://cdn.fake.com/img/product-1.png",
  "description": "Product Description 1"
}

###
POST http://localhost:3001/api/product
Content-Type: application/json

{
  "type": "EVENT",
  "price": 39.99,
  "stock": 12,
  "thumbnail": "https://cdn.fake.com/img/product-3.png",
  "description": "Event Description 2"
}

###

### Bad request by product type
POST http://localhost:3001/api/product
Content-Type: application/json

{
  "type": "EVENTS",
  "price": 39.99,
  "stock": 12,
  "thumbnail": "https://cdn.fake.com/img/product-3.png",
  "description": "Event Description 2"
}

###

### Bad request by price primitive type
POST http://localhost:3001/api/product
Content-Type: application/json

{
  "type": "EVENT",
  "price": "hello",
  "stock": 12,
  "thumbnail": "https://cdn.fake.com/img/product-3.png",
  "description": "Event Description 2"
}

###
