### Create new user
POST http://localhost:3001/api/user
Content-Type: application/json

{
  "firstName": "Daniel",
  "lastName": "Cruz"
}

###

### Bad request by required lastname
POST http://localhost:3001/api/user
Content-Type: application/json

{
  "firstName": "Daniel"
}

###
